// Editor themes inspired by VS Code and JetBrains

export const editorThemes = {
  'default-dark': {
    name: 'Default Dark',
    base: 'vs-dark',
    colors: {
      background: '#171717',
      foreground: '#E5E7EB',
      lineHighlight: '#262626',
      lineNumber: '#6B7280',
      lineNumberActive: '#A78BFA',
    },
    rules: [
      { token: 'comment', foreground: '6B7280', fontStyle: 'italic' },
      { token: 'keyword', foreground: 'C084FC', fontStyle: 'bold' },
      { token: 'string', foreground: '6EE7B7' },
      { token: 'number', foreground: 'FCD34D' },
      { token: 'type', foreground: '60A5FA' },
      { token: 'function', foreground: 'A78BFA' },
      { token: 'variable', foreground: 'E5E7EB' },
      { token: 'operator', foreground: 'F472B6' },
      { token: 'delimiter', foreground: 'D1D5DB' },
    ],
  },
  'vs-dark': {
    name: 'Dark+ (VS Code)',
    base: 'vs-dark',
    colors: {
      background: '#1E1E1E',
      foreground: '#D4D4D4',
      lineHighlight: '#2A2A2A',
      lineNumber: '#858585',
      lineNumberActive: '#C6C6C6',
    },
    rules: [
      { token: 'comment', foreground: '6A9955', fontStyle: 'italic' },
      { token: 'keyword', foreground: '569CD6', fontStyle: 'bold' },
      { token: 'string', foreground: 'CE9178' },
      { token: 'number', foreground: 'B5CEA8' },
      { token: 'type', foreground: '4EC9B0' },
      { token: 'function', foreground: 'DCDCAA' },
      { token: 'variable', foreground: '9CDCFE' },
      { token: 'operator', foreground: 'D4D4D4' },
      { token: 'delimiter', foreground: 'D4D4D4' },
    ],
  },
  'one-dark': {
    name: 'One Dark Pro',
    base: 'vs-dark',
    colors: {
      background: '#282C34',
      foreground: '#ABB2BF',
      lineHighlight: '#2C313A',
      lineNumber: '#495162',
      lineNumberActive: '#ABB2BF',
    },
    rules: [
      { token: 'comment', foreground: '5C6370', fontStyle: 'italic' },
      { token: 'keyword', foreground: 'C678DD', fontStyle: 'bold' },
      { token: 'string', foreground: '98C379' },
      { token: 'number', foreground: 'D19A66' },
      { token: 'type', foreground: 'E5C07B' },
      { token: 'function', foreground: '61AFEF' },
      { token: 'variable', foreground: 'E06C75' },
      { token: 'operator', foreground: '56B6C2' },
      { token: 'delimiter', foreground: 'ABB2BF' },
    ],
  },
  'dracula': {
    name: 'Dracula',
    base: 'vs-dark',
    colors: {
      background: '#282A36',
      foreground: '#F8F8F2',
      lineHighlight: '#44475A',
      lineNumber: '#6272A4',
      lineNumberActive: '#F8F8F2',
    },
    rules: [
      { token: 'comment', foreground: '6272A4', fontStyle: 'italic' },
      { token: 'keyword', foreground: 'FF79C6', fontStyle: 'bold' },
      { token: 'string', foreground: 'F1FA8C' },
      { token: 'number', foreground: 'BD93F9' },
      { token: 'type', foreground: '8BE9FD' },
      { token: 'function', foreground: '50FA7B' },
      { token: 'variable', foreground: 'F8F8F2' },
      { token: 'operator', foreground: 'FF79C6' },
      { token: 'delimiter', foreground: 'F8F8F2' },
    ],
  },
  'github-dark': {
    name: 'GitHub Dark',
    base: 'vs-dark',
    colors: {
      background: '#0D1117',
      foreground: '#C9D1D9',
      lineHighlight: '#161B22',
      lineNumber: '#484F58',
      lineNumberActive: '#C9D1D9',
    },
    rules: [
      { token: 'comment', foreground: '8B949E', fontStyle: 'italic' },
      { token: 'keyword', foreground: 'FF7B72', fontStyle: 'bold' },
      { token: 'string', foreground: 'A5D6FF' },
      { token: 'number', foreground: '79C0FF' },
      { token: 'type', foreground: 'FFA657' },
      { token: 'function', foreground: 'D2A8FF' },
      { token: 'variable', foreground: 'FFA657' },
      { token: 'operator', foreground: 'FF7B72' },
      { token: 'delimiter', foreground: 'C9D1D9' },
    ],
  },
  'monokai': {
    name: 'Monokai',
    base: 'vs-dark',
    colors: {
      background: '#272822',
      foreground: '#F8F8F2',
      lineHighlight: '#3E3D32',
      lineNumber: '#90908A',
      lineNumberActive: '#F8F8F2',
    },
    rules: [
      { token: 'comment', foreground: '75715E', fontStyle: 'italic' },
      { token: 'keyword', foreground: 'F92672', fontStyle: 'bold' },
      { token: 'string', foreground: 'E6DB74' },
      { token: 'number', foreground: 'AE81FF' },
      { token: 'type', foreground: '66D9EF' },
      { token: 'function', foreground: 'A6E22E' },
      { token: 'variable', foreground: 'F8F8F2' },
      { token: 'operator', foreground: 'F92672' },
      { token: 'delimiter', foreground: 'F8F8F2' },
    ],
  },
  'jetbrains-dark': {
    name: 'JetBrains Darcula',
    base: 'vs-dark',
    colors: {
      background: '#2B2B2B',
      foreground: '#A9B7C6',
      lineHighlight: '#323232',
      lineNumber: '#606366',
      lineNumberActive: '#A4A3A3',
    },
    rules: [
      { token: 'comment', foreground: '808080', fontStyle: 'italic' },
      { token: 'keyword', foreground: 'CC7832', fontStyle: 'bold' },
      { token: 'string', foreground: '6A8759' },
      { token: 'number', foreground: '6897BB' },
      { token: 'type', foreground: 'FFC66D' },
      { token: 'function', foreground: 'FFC66D' },
      { token: 'variable', foreground: 'A9B7C6' },
      { token: 'operator', foreground: 'A9B7C6' },
      { token: 'delimiter', foreground: 'A9B7C6' },
    ],
  },
  'default-light': {
    name: 'Default Light',
    base: 'vs',
    colors: {
      background: '#FFFFFF',
      foreground: '#1F2937',
      lineHighlight: '#F5F5F5',
      lineNumber: '#6B7280',
      lineNumberActive: '#7C3AED',
    },
    rules: [
      { token: 'comment', foreground: '6B7280', fontStyle: 'italic' },
      { token: 'keyword', foreground: '7C3AED', fontStyle: 'bold' },
      { token: 'string', foreground: '059669' },
      { token: 'number', foreground: 'D97706' },
      { token: 'type', foreground: '2563EB' },
      { token: 'function', foreground: '7C3AED' },
      { token: 'variable', foreground: '1F2937' },
      { token: 'operator', foreground: 'DB2777' },
      { token: 'delimiter', foreground: '4B5563' },
    ],
  },
  'vs-light': {
    name: 'Light+ (VS Code)',
    base: 'vs',
    colors: {
      background: '#FFFFFF',
      foreground: '#000000',
      lineHighlight: '#F5F5F5',
      lineNumber: '#237893',
      lineNumberActive: '#000000',
    },
    rules: [
      { token: 'comment', foreground: '008000', fontStyle: 'italic' },
      { token: 'keyword', foreground: '0000FF', fontStyle: 'bold' },
      { token: 'string', foreground: 'A31515' },
      { token: 'number', foreground: '098658' },
      { token: 'type', foreground: '267F99' },
      { token: 'function', foreground: '795E26' },
      { token: 'variable', foreground: '001080' },
      { token: 'operator', foreground: '000000' },
      { token: 'delimiter', foreground: '000000' },
    ],
  },
  'github-light': {
    name: 'GitHub Light',
    base: 'vs',
    colors: {
      background: '#FFFFFF',
      foreground: '#24292F',
      lineHighlight: '#F6F8FA',
      lineNumber: '#57606A',
      lineNumberActive: '#24292F',
    },
    rules: [
      { token: 'comment', foreground: '6E7781', fontStyle: 'italic' },
      { token: 'keyword', foreground: 'CF222E', fontStyle: 'bold' },
      { token: 'string', foreground: '0A3069' },
      { token: 'number', foreground: '0550AE' },
      { token: 'type', foreground: '953800' },
      { token: 'function', foreground: '8250DF' },
      { token: 'variable', foreground: '953800' },
      { token: 'operator', foreground: 'CF222E' },
      { token: 'delimiter', foreground: '24292F' },
    ],
  },
  'solarized-light': {
    name: 'Solarized Light',
    base: 'vs',
    colors: {
      background: '#FDF6E3',
      foreground: '#657B83',
      lineHighlight: '#EEE8D5',
      lineNumber: '#93A1A1',
      lineNumberActive: '#657B83',
    },
    rules: [
      { token: 'comment', foreground: '93A1A1', fontStyle: 'italic' },
      { token: 'keyword', foreground: '859900', fontStyle: 'bold' },
      { token: 'string', foreground: '2AA198' },
      { token: 'number', foreground: 'D33682' },
      { token: 'type', foreground: 'B58900' },
      { token: 'function', foreground: '268BD2' },
      { token: 'variable', foreground: '657B83' },
      { token: 'operator', foreground: '859900' },
      { token: 'delimiter', foreground: '657B83' },
    ],
  },
};

