// Syntax highlighting color presets and token types

export const syntaxColorPresets = {
  'default': {
    name: 'Default',
    dark: {
      comment: '6B7280',
      keyword: 'C084FC',
      string: '6EE7B7',
      number: 'FCD34D',
      type: '60A5FA',
      function: 'A78BFA',
      variable: 'E5E7EB',
      operator: 'F472B6',
    },
    light: {
      comment: '6B7280',
      keyword: '7C3AED',
      string: '059669',
      number: 'D97706',
      type: '2563EB',
      function: '7C3AED',
      variable: '1F2937',
      operator: 'DB2777',
    },
  },
  'ocean': {
    name: 'Ocean',
    dark: {
      comment: '546E7A',
      keyword: '89DDFF',
      string: 'C3E88D',
      number: 'F78C6C',
      type: 'FFCB6B',
      function: '82AAFF',
      variable: 'EEFFFF',
      operator: '89DDFF',
    },
    light: {
      comment: '546E7A',
      keyword: '6182B8',
      string: '91B859',
      number: 'F76D47',
      type: 'E2931D',
      function: '6182B8',
      variable: '37474F',
      operator: '39ADB5',
    },
  },
  'sunset': {
    name: 'Sunset',
    dark: {
      comment: '8B8B8B',
      keyword: 'FF6B6B',
      string: 'FFE66D',
      number: 'FF8E72',
      type: '4ECDC4',
      function: 'C792EA',
      variable: 'F8F8F2',
      operator: 'FF6B6B',
    },
    light: {
      comment: '8B8B8B',
      keyword: 'D63031',
      string: 'FDCB6E',
      number: 'E17055',
      type: '00B894',
      function: '6C5CE7',
      variable: '2D3436',
      operator: 'D63031',
    },
  },
  'forest': {
    name: 'Forest',
    dark: {
      comment: '608B4E',
      keyword: '4EC9B0',
      string: 'CE9178',
      number: 'B5CEA8',
      type: '4FC1FF',
      function: 'DCDCAA',
      variable: '9CDCFE',
      operator: 'D4D4D4',
    },
    light: {
      comment: '008000',
      keyword: '008080',
      string: 'A31515',
      number: '098658',
      type: '267F99',
      function: '795E26',
      variable: '001080',
      operator: '000000',
    },
  },
  'neon': {
    name: 'Neon',
    dark: {
      comment: '6272A4',
      keyword: 'FF79C6',
      string: 'F1FA8C',
      number: 'BD93F9',
      type: '8BE9FD',
      function: '50FA7B',
      variable: 'F8F8F2',
      operator: 'FF79C6',
    },
    light: {
      comment: '6272A4',
      keyword: 'DB2777',
      string: 'CA8A04',
      number: '7C3AED',
      type: '0891B2',
      function: '16A34A',
      variable: '1F2937',
      operator: 'DB2777',
    },
  },
};

// Token types for syntax highlighting
export const syntaxTokenTypes = [
  { key: 'keyword', label: 'Keywords', example: 'const, function, if' },
  { key: 'string', label: 'Strings', example: '"hello world"' },
  { key: 'number', label: 'Numbers', example: '42, 3.14' },
  { key: 'comment', label: 'Comments', example: '// comment' },
  { key: 'function', label: 'Functions', example: 'myFunction()' },
  { key: 'type', label: 'Types', example: 'String, Number' },
  { key: 'variable', label: 'Variables', example: 'myVar' },
  { key: 'operator', label: 'Operators', example: '+, -, =, =>' },
];

